sudo: required

services:
    - docker

before_install:
    - docker pull nimlang/nim

jobs:
    include:
        - stage: check
          script:
            - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble check"
        - stage: test
          script:
            - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble test"
        - stage: install
          script:
            - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble install -dy"
